version: "1.2"

services:
  mysqldb:
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - mysqldb

  # db:
  #   container_name: pg_container
  #   image: postgres:latest
  #   restart: always
  #   environment: 
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_USER: root
  #   ports: 
  #     - "5432:5432"
  #   volumes: 
  #     - postgresql:/var/lib/postgresql/data
  
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"

# volumes: 
#   postgresql: {}
